### ISSUE TITLE
It doesn't work when the replaced word is more than one word long

### ISSUE THREAD

**Issue by thalesmello** [AndrewRadev/multichange.vim#2]
Suppose I have the following snippet

```
" Denite
Plug 'Shougo/denite.nvim'
Plug 'chemzqm/unite-location'
Plug 'thalesmello/config-unite-outline'
Plug 'Shougo/unite-outline'
```

If I multichange this paragraph, and change the word, by pressing `cwhello world` at the start of any plug word, the result would be:

```
" Denite
hello world 'Shougo/denite.nvim'
world 'chemzqm/unite-location'
world 'thalesmello/config-unite-outline'
world 'Shougo/unite-outline'
```

It gets weirder if the composed word is actually an expension of the previously selected text.
If I were to type `cwPlug More`, the result would be

```
" Denite
More More 'Shougo/denite.nvim'
More 'chemzqm/unite-location'
More 'thalesmello/config-unite-outline'
More 'Shougo/unite-outline'
```

Notice the duplicated `More`.

**Comment by AndrewRadev** [comment]
For words, the plugin was assuming that you're replacing a word with another word. A bit naive, I admit, but I usually use it for replacing either variables (where this works), or replacing phrases in visual mode (where the replacement is taken from the last-entered-text).

Considering multi-word changing works correctly in visual mode, you'd think it'd be easy to port to normal mode, but visual mode gives you nice start and end marks to work with, it's trickier in normal mode. Still, by saving the starting position manually, it seems I've gotten it to work. Could you check it out and let me know if it works for you, too?

As for the duplicated content, this one is trickier. The plugin runs a substitution to do the replacement, and when you replace, say "foo" with "foo bar", it tries to replace any "foo" in the range with "foo bar". And since you've already typed "foo bar", your just-typed "foo" gets replaced as well. One possibility is to add the line and column in some sort of negative-lookbehind pattern, and I've tried to do that in the past (and also just now), but it got complicated. I'll see what I can do.

**Comment by thalesmello** [comment]
:+1: I can confirm it works.

Thanks for the quick reply. I will close this issue, as this issue with this thread has already been solved.

I will open another one regarding the duplication.
